config/routes.rb
Rails.application.routes.draw do
  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  resources :users
  root to: 'users#new'

  get "sessions/new"
  get "sessions/create"
  get "sessions/destroy"

  POST "sessions/create"

end

app/models/user.rb
class User < ActiveRecord::Base
	before_validation :prep_email
	before_save :create_avatar_url

	def create_avatar_url
   		self.avatar_url = "http://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(self.email)}?s=50"
	end


	has_secure_password

	validates :name, presence: true
	validates :username, uniqueness: true, presence: true
	validates :email, uniqueness: true, presence: true, format: { with: /\A[\w.+-]+@([\w]+.)+\w+\z/ }

	private

	def prep_email
   		self.email = self.email.strip.downcase if self.email
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

	def current_user
   @current_user ||= User.find(session[:user_id]) if session[:user_id]
end

helper_method :current_user
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
   user = User.find_by_username(params[:username])
   if user && user.authenticate(params[:password])
       session[:userid] = user.id
       redirect_to rooturl, notice: "Logged in!"
   else
       flash[:error] = "Wrong Username or Password."
       redirect_to root_url
   end
	end

  def destroy
	   session[:userid] = nil
   	   redirect_to root_url, notice: "Logged out."
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	def new
   		@user = User.new
	end

	def create
		@user = User.new(params[:user])

 			if @user.save
 				session[:user_id] = @user.id
   				redirect_to @user, notice: "Thank you for signing up for Ribbit!"
 			else
   				render 'new'
 			end
	end

	def show
		@user = User.find(params[:id])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tuningpeople</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>

<% if current_user %>
   <%= link_to "Log Out", sessions_destroy_path %>
<% else %>
   <%= form_tag sessions_create_path do %>
       <%= text_field_tag :username, nil, placeholder: "username" %>
       <%= password_field_tag :password, nil,  placeholder: "password" %>
       <%= submit_tag "Log In" %>
   <% end %>
<% end %>
<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<img src="/gfx/images.jpg">

<div class="panel right">
 <h1>New to Tuning people</h1>
  
 <%= form_for @user do |f| %>
   <% if @user.errors.any? %>
     <ul>
       <% @user.errors.full_messages.each do |message| %>
         <li><%= message %></li>
       <% end %>
     </ul>
   <% end %>

   <%= f.text_field :email, placeholder: "email" %> <br />
   <%= f.text_field :username, placeholder: "username" %> <br />
   <%= f.text_field :name, placeholder: "name" %> <br />
   <%= f.password_field :password, placeholder: "password" %> <br />
   <%= f.password_field :password_confirmation, placeholder: "password" %> <br />
   <%= f.submit "Create Account" %> <br />
 <% end %>
</div>

app/views/users/show.html.erb
<div id="createRibbit" class="panel right">
   <h1>Get Tuned</h1>
   <p>
   <form>
       <textarea name="text" class="ribbitText"></textarea>
       <input type="submit" value="Ribbit!">
   </form>
   </p>
</div>
<div id="tunes" class="panel left">
   <h1>Your Tuned Profile</h1>
   <div class="tuningWrapper">
       <img class="avatar" src="<%= @user.avatar_url %>">
       <span class="name"><%= @user.name %></span> @<%= @user.username %>
       <p>
       XX Tunes
       <span class="spacing">XX Followers</span>
       <span class="spacing">XX Following</span>
       </p>
   </div>
</div>
<div class="panel left">
   <h1>Your Tunes</h1>
   <div class="tuningWrapper">
       Tunes coming . . .
   </div>
</div>
 